# Generated by Django 2.2.2 on 2019-06-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0003_auto_20190613_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelreport',
            name='eastside_all_fire_acres',
            field=models.IntegerField(default=10, help_text='How many acres burned on the eastside?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intelreport',
            name='eastside_dnr_fire_acres',
            field=models.IntegerField(default=10, help_text='How many DNR Fire acres burned on the eastside?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intelreport',
            name='eastside_dnr_fire_count',
            field=models.IntegerField(default=10, help_text='How many DNR Fires total on the eastside?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intelreport',
            name='eastside_dnr_responses_count',
            field=models.IntegerField(default=10, help_text='How many DNR Responses total on the eastside?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intelreport',
            name='westside_all_fire_acres',
            field=models.IntegerField(default=10, help_text='How many acres burned on the westside?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intelreport',
            name='westside_dnr_fire_acres',
            field=models.IntegerField(default=10, help_text='How many DNR Fire acres burned on the westside?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intelreport',
            name='westside_dnr_fire_count',
            field=models.IntegerField(default=10, help_text='How many DNR Fires total on the westside?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intelreport',
            name='westside_dnr_responses_count',
            field=models.IntegerField(default=10, help_text='How many DNR Responses total on the westside?'),
            preserve_default=False,
        ),
    ]
