# Generated by Django 2.2.2 on 2019-06-29 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0004_auto_20190614_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelreport',
            name='dnr_ia_fires',
            field=models.IntegerField(help_text='How many DNR-based IA fires are there currently?', verbose_name='DNR IA Fires'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_all_fire_acres',
            field=models.IntegerField(help_text='How many acres burned on the eastside?', verbose_name='YTD Eastside All Acres'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_dnr_fire_acres',
            field=models.IntegerField(help_text='How many DNR Fire acres burned on the eastside?', verbose_name='YTD Eastside DNR Fire Acres'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_dnr_fire_count',
            field=models.IntegerField(help_text='How many DNR Fires total on the eastside?', verbose_name='YTD Eastside DNR Fires'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_dnr_responses_count',
            field=models.IntegerField(help_text='How many DNR Responses total on the eastside?', verbose_name='YTD Eastside DNR Responses'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='oly_committed_crews',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='OLS In Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='oly_committed_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='OLS In Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='preparedness_level_national',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text="What's the national preparedness level? (out of 5)", verbose_name='National Preparedness Level'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='preparedness_level_nw',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text="What's the curernt NW GACC preparedness level? (out of 5)", verbose_name='Northwest Preparedness Level'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='type_1_teams_assigned',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='How many out of the five Type 1 teams are currently assigned?', verbose_name='Type 1 Teams Assigned'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='type_2_teams_assigned',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], help_text='How many out of the eight Type 2 teams are currently assigned?', verbose_name='Type 2 Teams Assigned'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='wa_large_fires',
            field=models.IntegerField(help_text='How many WA-based large fires are there currently?', verbose_name='Washington Large Fires'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_all_fire_acres',
            field=models.IntegerField(help_text='How many acres burned on the westside?', verbose_name='YTD Westside All Acres'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_dnr_fire_acres',
            field=models.IntegerField(help_text='How many DNR Fire acres burned on the westside?', verbose_name='YTD Westside DNR Fire Acres'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_dnr_fire_count',
            field=models.IntegerField(help_text='How many DNR Fires total on the westside?', verbose_name='YTD Westside DNR Fires'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_dnr_responses_count',
            field=models.IntegerField(help_text='How many DNR Responses total on the westside?', verbose_name='YTD Westside DNR Responses'),
        ),
    ]
