# Generated by Django 2.2.2 on 2019-06-30 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0005_auto_20190629_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_all_fire_acres',
            field=models.IntegerField(verbose_name='YTD Eastside All Acres'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_atgs',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eastside ATGS'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_dnr_fire_acres',
            field=models.IntegerField(verbose_name='YTD Eastside DNR Fire Acres'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_dnr_fire_count',
            field=models.IntegerField(verbose_name='YTD Eastside DNR Fires'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_dnr_responses_count',
            field=models.IntegerField(verbose_name='YTD Eastside DNR Responses'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_firebosses',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eastside SEATs'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='eastside_rotors',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eastside Helicopters'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='in_region_lat',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='In Region LATs'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='in_region_vlat',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='In Region VLATs'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='ne_available_crews',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='NES Out of Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='ne_available_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='NES Out of Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='ne_committed_crews',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='NES In Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='ne_committed_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='NES In Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='nw_available_crews',
            field=models.SmallIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='NWS Out of Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='nw_available_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='NWS Out of Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='nw_committed_crews',
            field=models.SmallIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='NWS In Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='nw_committed_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='NWS In Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='oly_available_crews',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='OLS Out of Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='oly_available_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='OLS Out of Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='pc_available_crews',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='PCS Out of Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='pc_available_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='PCS Out of Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='pc_committed_crews',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='PCS In Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='pc_committed_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='PCS In Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='se_available_crews',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='SES Out of Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='se_available_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='SES Out of Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='se_committed_crews',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='SES In Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='se_committed_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='SES In Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='sps_available_crews',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='SPS Out of Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='sps_available_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='SPS Out of Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='sps_committed_crews',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='SPS In Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='sps_committed_engines',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='SPS In Region Engines'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_all_fire_acres',
            field=models.IntegerField(verbose_name='YTD Westside All Acres'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_atgs',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Westside ATGS'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_dnr_fire_acres',
            field=models.IntegerField(verbose_name='YTD Westside DNR Fire Acres'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_dnr_fire_count',
            field=models.IntegerField(verbose_name='YTD Westside DNR Fires'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_dnr_responses_count',
            field=models.IntegerField(verbose_name='YTD Westside DNR Responses'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_firebosses',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Westside SEATs'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='westside_rotors',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Westside Helicopters'),
        ),
    ]
