# Generated by Django 2.2.2 on 2019-06-30 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0006_auto_20190629_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelreport',
            name='nw_available_crews',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='NWS Out of Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='nw_committed_crews',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='NWS In Region Crews'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='preparedness_level_national',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='What is the national preparedness level? (out of 5)', verbose_name='National Preparedness Level'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='preparedness_level_nw',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='What is the current NW GACC preparedness level? (out of 5)', verbose_name='Northwest Preparedness Level'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='type_1_teams_assigned',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='How many NW Type 1 teams are currently assigned?', verbose_name='Type 1 Teams Assigned'),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='type_2_teams_assigned',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], help_text='How many NW Type 2 teams are currently assigned?', verbose_name='Type 2 Teams Assigned'),
        ),
    ]
