# Generated by Django 2.2.2 on 2019-07-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0007_auto_20190630_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='AviationDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(default='Adam Jones', max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_cost_sheet', models.BooleanField(default=False, help_text='Is this uploaded document a Cost Sheet?')),
            ],
        ),
        migrations.CreateModel(
            name='AviationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(default='Adam Jones', max_length=50)),
                ('notes', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='date_of_report',
            field=models.DateTimeField(help_text="REMEMBER - the latest date's Fire Intel is always shown in the application. The date should always be 'today' and 'now', but if you need to update values be sure to update the date too"),
        ),
    ]
