# Generated by Django 2.2.2 on 2019-07-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0008_auto_20190716_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviationdoc',
            name='file_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aviationdoc',
            name='file_upload',
            field=models.FileField(default='test', upload_to='archives/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aviationlog',
            name='notes',
            field=models.TextField(max_length=500),
        ),
    ]
