# Generated by Django 2.2.3 on 2019-07-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0009_auto_20190719_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviationdoc',
            name='file_upload',
            field=models.FileField(upload_to='aviation_docs/'),
        ),
    ]
