# Generated by Django 2.2.2 on 2020-05-29 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0010_auto_20190719_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='AviationIntelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report', models.DateTimeField(help_text="REMEMBER - the latest date's Fire Intel is always shown in the application by data type. The date should always be 'today' and 'now', but if you need to update values be sure to update the date too")),
                ('westside_rotors', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Westside Helicopters')),
                ('westside_firebosses', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Westside SEATs')),
                ('westside_atgs', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Westside ATGS')),
                ('eastside_rotors', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eastside Helicopters')),
                ('eastside_firebosses', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eastside SEATs')),
                ('eastside_atgs', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eastside ATGS')),
                ('in_region_vlat', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='In Region VLATs')),
                ('in_region_lat', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='In Region LATs')),
            ],
            options={
                'verbose_name': 'Aviation Intel Report',
                'verbose_name_plural': 'Aviation Intel Reports',
            },
        ),
        migrations.CreateModel(
            name='NortheastRegionIntelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report', models.DateTimeField(help_text="REMEMBER - the latest date's Fire Intel is always shown in the application by data type. The date should always be 'today' and 'now', but if you need to update values be sure to update the date too")),
                ('new_initial_attack', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='New Initial Attack Fire Counts')),
                ('new_ia_acres', models.DecimalField(decimal_places=2, help_text='Value is rounded to two decimals places', max_digits=8, verbose_name='New Initial Attack Acres')),
                ('region_large_fires', models.IntegerField(help_text='How many WA-based large fires are there currently in your region', verbose_name='Current Number of Large Fires in Region')),
                ('committed_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Engines')),
                ('committed_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Crews')),
                ('available_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Engines')),
                ('available_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Crews')),
                ('dnr_region', models.CharField(default='NE', editable=False, max_length=3, verbose_name='DNR Region Name')),
            ],
            options={
                'verbose_name': 'NE Region Intel Report',
                'verbose_name_plural': 'NE Region Intel Reports',
            },
        ),
        migrations.CreateModel(
            name='NorthwestRegionIntelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report', models.DateTimeField(help_text="REMEMBER - the latest date's Fire Intel is always shown in the application by data type. The date should always be 'today' and 'now', but if you need to update values be sure to update the date too")),
                ('new_initial_attack', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='New Initial Attack Fire Counts')),
                ('new_ia_acres', models.DecimalField(decimal_places=2, help_text='Value is rounded to two decimals places', max_digits=8, verbose_name='New Initial Attack Acres')),
                ('region_large_fires', models.IntegerField(help_text='How many WA-based large fires are there currently in your region', verbose_name='Current Number of Large Fires in Region')),
                ('committed_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Engines')),
                ('committed_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Crews')),
                ('available_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Engines')),
                ('available_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Crews')),
                ('dnr_region', models.CharField(default='NW', editable=False, max_length=3, verbose_name='DNR Region Name')),
            ],
            options={
                'verbose_name': 'NW Region Intel Report',
                'verbose_name_plural': 'NW Region Intel Reports',
            },
        ),
        migrations.CreateModel(
            name='OlympicRegionIntelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report', models.DateTimeField(help_text="REMEMBER - the latest date's Fire Intel is always shown in the application by data type. The date should always be 'today' and 'now', but if you need to update values be sure to update the date too")),
                ('new_initial_attack', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='New Initial Attack Fire Counts')),
                ('new_ia_acres', models.DecimalField(decimal_places=2, help_text='Value is rounded to two decimals places', max_digits=8, verbose_name='New Initial Attack Acres')),
                ('region_large_fires', models.IntegerField(help_text='How many WA-based large fires are there currently in your region', verbose_name='Current Number of Large Fires in Region')),
                ('committed_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Engines')),
                ('committed_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Crews')),
                ('available_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Engines')),
                ('available_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Crews')),
                ('dnr_region', models.CharField(default='OLY', editable=False, max_length=3, verbose_name='DNR Region Name')),
            ],
            options={
                'verbose_name': 'OLY Region Intel Report',
                'verbose_name_plural': 'OLY Region Intel Reports',
            },
        ),
        migrations.CreateModel(
            name='OverviewIntelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report', models.DateTimeField(help_text="REMEMBER - the latest date's Fire Intel is always shown in the application by data type. The date should always be 'today' and 'now', but if you need to update values be sure to update the date too")),
                ('preparedness_level_national', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='What is the national preparedness level? (out of 5)', verbose_name='National Preparedness Level')),
                ('preparedness_level_nw', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='What is the current NW GACC preparedness level? (out of 5)', verbose_name='Northwest Preparedness Level')),
                ('type_1_teams_assigned', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='How many NW Type 1 teams are currently assigned?', verbose_name='Type 1 Teams Assigned')),
                ('type_2_teams_assigned', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], help_text='How many NW Type 2 teams are currently assigned?', verbose_name='Type 2 Teams Assigned')),
                ('westside_dnr_responses_count', models.IntegerField(verbose_name='YTD Westside DNR Responses')),
                ('westside_dnr_fire_count', models.IntegerField(verbose_name='YTD Westside DNR Fires')),
                ('westside_dnr_fire_acres', models.IntegerField(verbose_name='YTD Westside DNR Fire Acres')),
                ('westside_all_fire_acres', models.IntegerField(verbose_name='YTD Westside All Acres')),
                ('eastside_dnr_responses_count', models.IntegerField(verbose_name='YTD Eastside DNR Responses')),
                ('eastside_dnr_fire_count', models.IntegerField(verbose_name='YTD Eastside DNR Fires')),
                ('eastside_dnr_fire_acres', models.IntegerField(verbose_name='YTD Eastside DNR Fire Acres')),
                ('eastside_all_fire_acres', models.IntegerField(verbose_name='YTD Eastside All Acres')),
            ],
            options={
                'verbose_name': 'Overview Intel Report',
                'verbose_name_plural': 'Overview Intel Reports',
            },
        ),
        migrations.CreateModel(
            name='PacificCascadeRegionIntelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report', models.DateTimeField(help_text="REMEMBER - the latest date's Fire Intel is always shown in the application by data type. The date should always be 'today' and 'now', but if you need to update values be sure to update the date too")),
                ('new_initial_attack', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='New Initial Attack Fire Counts')),
                ('new_ia_acres', models.DecimalField(decimal_places=2, help_text='Value is rounded to two decimals places', max_digits=8, verbose_name='New Initial Attack Acres')),
                ('region_large_fires', models.IntegerField(help_text='How many WA-based large fires are there currently in your region', verbose_name='Current Number of Large Fires in Region')),
                ('committed_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Engines')),
                ('committed_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Crews')),
                ('available_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Engines')),
                ('available_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Crews')),
                ('dnr_region', models.CharField(default='PC', editable=False, max_length=3, verbose_name='DNR Region Name')),
            ],
            options={
                'verbose_name': 'PC Region Intel Report',
                'verbose_name_plural': 'PC Region Intel Reports',
            },
        ),
        migrations.CreateModel(
            name='SoutheastRegionIntelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report', models.DateTimeField(help_text="REMEMBER - the latest date's Fire Intel is always shown in the application by data type. The date should always be 'today' and 'now', but if you need to update values be sure to update the date too")),
                ('new_initial_attack', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='New Initial Attack Fire Counts')),
                ('new_ia_acres', models.DecimalField(decimal_places=2, help_text='Value is rounded to two decimals places', max_digits=8, verbose_name='New Initial Attack Acres')),
                ('region_large_fires', models.IntegerField(help_text='How many WA-based large fires are there currently in your region', verbose_name='Current Number of Large Fires in Region')),
                ('committed_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Engines')),
                ('committed_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Crews')),
                ('available_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Engines')),
                ('available_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Crews')),
                ('dnr_region', models.CharField(default='SE', editable=False, max_length=3, verbose_name='DNR Region Name')),
            ],
            options={
                'verbose_name': 'SE Region Intel Report',
                'verbose_name_plural': 'SE Region Intel Reports',
            },
        ),
        migrations.CreateModel(
            name='SouthPugetSoundRegionIntelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report', models.DateTimeField(help_text="REMEMBER - the latest date's Fire Intel is always shown in the application by data type. The date should always be 'today' and 'now', but if you need to update values be sure to update the date too")),
                ('new_initial_attack', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='New Initial Attack Fire Counts')),
                ('new_ia_acres', models.DecimalField(decimal_places=2, help_text='Value is rounded to two decimals places', max_digits=8, verbose_name='New Initial Attack Acres')),
                ('region_large_fires', models.IntegerField(help_text='How many WA-based large fires are there currently in your region', verbose_name='Current Number of Large Fires in Region')),
                ('committed_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Engines')),
                ('committed_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='In Region Crews')),
                ('available_engines', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Engines')),
                ('available_crews', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Out of Region Crews')),
                ('dnr_region', models.CharField(default='SPS', editable=False, max_length=3, verbose_name='DNR Region Name')),
            ],
            options={
                'verbose_name': 'SPS Region Intel Report',
                'verbose_name_plural': 'SPS Region Intel Reports',
            },
        ),
        migrations.DeleteModel(
            name='AviationDoc',
        ),
        migrations.DeleteModel(
            name='AviationLog',
        ),
        migrations.DeleteModel(
            name='IntelReport',
        ),
    ]
