# Generated by Django 2.2.2 on 2020-05-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0011_auto_20200528_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='northeastregionintelreport',
            name='total_dnr_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='To-date value comes from EIRS data, also value is rounded to two decimals places', max_digits=10, verbose_name='Total DNR Acres Burned in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='northeastregionintelreport',
            name='total_dnr_fires',
            field=models.IntegerField(default=10, help_text='To-date value, how many DNR fires are reported in EIRS?', verbose_name='Total DNR Fires in Region to-date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='northeastregionintelreport',
            name='total_response_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Value is rounded to two decimals places', max_digits=10, verbose_name='Total Response Acres in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='northeastregionintelreport',
            name='total_responses',
            field=models.IntegerField(default=10, help_text='To-date value, how many responses are reported in EIRS?', verbose_name='Total Responses in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='northwestregionintelreport',
            name='total_dnr_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='To-date value comes from EIRS data, also value is rounded to two decimals places', max_digits=10, verbose_name='Total DNR Acres Burned in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='northwestregionintelreport',
            name='total_dnr_fires',
            field=models.IntegerField(default=10, help_text='To-date value, how many DNR fires are reported in EIRS?', verbose_name='Total DNR Fires in Region to-date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='northwestregionintelreport',
            name='total_response_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Value is rounded to two decimals places', max_digits=10, verbose_name='Total Response Acres in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='northwestregionintelreport',
            name='total_responses',
            field=models.IntegerField(default=10, help_text='To-date value, how many responses are reported in EIRS?', verbose_name='Total Responses in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olympicregionintelreport',
            name='total_dnr_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='To-date value comes from EIRS data, also value is rounded to two decimals places', max_digits=10, verbose_name='Total DNR Acres Burned in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olympicregionintelreport',
            name='total_dnr_fires',
            field=models.IntegerField(default=10, help_text='To-date value, how many DNR fires are reported in EIRS?', verbose_name='Total DNR Fires in Region to-date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olympicregionintelreport',
            name='total_response_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Value is rounded to two decimals places', max_digits=10, verbose_name='Total Response Acres in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olympicregionintelreport',
            name='total_responses',
            field=models.IntegerField(default=10, help_text='To-date value, how many responses are reported in EIRS?', verbose_name='Total Responses in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacificcascaderegionintelreport',
            name='total_dnr_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='To-date value comes from EIRS data, also value is rounded to two decimals places', max_digits=10, verbose_name='Total DNR Acres Burned in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacificcascaderegionintelreport',
            name='total_dnr_fires',
            field=models.IntegerField(default=10, help_text='To-date value, how many DNR fires are reported in EIRS?', verbose_name='Total DNR Fires in Region to-date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacificcascaderegionintelreport',
            name='total_response_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Value is rounded to two decimals places', max_digits=10, verbose_name='Total Response Acres in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacificcascaderegionintelreport',
            name='total_responses',
            field=models.IntegerField(default=10, help_text='To-date value, how many responses are reported in EIRS?', verbose_name='Total Responses in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='southeastregionintelreport',
            name='total_dnr_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='To-date value comes from EIRS data, also value is rounded to two decimals places', max_digits=10, verbose_name='Total DNR Acres Burned in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='southeastregionintelreport',
            name='total_dnr_fires',
            field=models.IntegerField(default=10, help_text='To-date value, how many DNR fires are reported in EIRS?', verbose_name='Total DNR Fires in Region to-date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='southeastregionintelreport',
            name='total_response_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Value is rounded to two decimals places', max_digits=10, verbose_name='Total Response Acres in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='southeastregionintelreport',
            name='total_responses',
            field=models.IntegerField(default=10, help_text='To-date value, how many responses are reported in EIRS?', verbose_name='Total Responses in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='southpugetsoundregionintelreport',
            name='total_dnr_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='To-date value comes from EIRS data, also value is rounded to two decimals places', max_digits=10, verbose_name='Total DNR Acres Burned in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='southpugetsoundregionintelreport',
            name='total_dnr_fires',
            field=models.IntegerField(default=10, help_text='To-date value, how many DNR fires are reported in EIRS?', verbose_name='Total DNR Fires in Region to-date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='southpugetsoundregionintelreport',
            name='total_response_acres',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Value is rounded to two decimals places', max_digits=10, verbose_name='Total Response Acres in Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='southpugetsoundregionintelreport',
            name='total_responses',
            field=models.IntegerField(default=10, help_text='To-date value, how many responses are reported in EIRS?', verbose_name='Total Responses in Region'),
            preserve_default=False,
        ),
    ]
