# Generated by Django 2.2.2 on 2020-06-01 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0012_auto_20200529_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewintelreport',
            name='fire_weather_doc',
            field=models.FileField(default='test', help_text='This will only accept PDF files!', upload_to='intel_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fire Weather Report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overviewintelreport',
            name='fuels_danger_report_doc',
            field=models.FileField(default='test', help_text='This will only accept PDF files!', upload_to='intel_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fuels/Fire Danger Report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overviewintelreport',
            name='intel_report_doc',
            field=models.FileField(default='test', help_text='This will only accept PDF files!', upload_to='intel_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Intelligence Report'),
            preserve_default=False,
        ),
    ]
