# Generated by Django 2.2 on 2020-06-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_intel', '0013_auto_20200531_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewintelreport',
            name='preparedness_level_dnr',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, help_text='What is the current DNR preparedness level? (out of 5)', verbose_name='DNR Preparedness Level'),
        ),
        migrations.AddField(
            model_name='overviewintelreport',
            name='type_3_teams_assigned',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0, help_text='How many Washington Type 3 teams are currently assigned?', verbose_name='Type 3 Teams Assigned'),
        ),
    ]
